import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Redux VS Zustand</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1>Redux VS Zustand</h1>
        <Link href={"/redux"}>
          <a className={styles.link}>Redux</a>
        </Link>
        <Link href={"/zustand"}>
          <a className={styles.link}>Zustand</a>
        </Link>
      </main>
    </div>
  );
}
