import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useTodoStore } from "../states/zustand/store";
import { useEffect, useState } from "react";
import Link from "next/link";
import { nanoid } from "nanoid";

const Zustand = () => {
  const [input, setInput] = useState("");
  const getTodos = useTodoStore((state) => state.getTodos);
  const todos = useTodoStore((state) => state.todos);
  const addTodo = useTodoStore((state) => state.addTodo);
  const removeTodo = useTodoStore((state) => state.removeTodo);
  const toggleTodo = useTodoStore((state) => state.toggleTodo);

  useEffect(() => {
    getTodos();
    console.log("Zustand useEffect triggered");
  }, [getTodos]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Zustand</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1>Zustand</h1>
        <Link href={"/"}>
          <a className={styles.link}>Home</a>
        </Link>
        <h1>{todos.length} todos.</h1>
        <form
          onSubmit={(e) => {
            e.preventDefault();
            addTodo({ text: input, id: nanoid(4), completed: false });
            setInput("");
          }}
        >
          <input type='text' onChange={(e) => setInput(e.target.value)} value={input} style={{ marginRight: "10px" }} />
          <button className={styles.btn}>add</button>
        </form>

        {todos?.map((todo) => (
          <div key={todo.id} className={styles.todo}>
            <p style={{ textDecoration: `${todo.completed ? "line-through" : ""}` }}>
              {todo.text} - {todo.id}
            </p>
            <button className={styles.btn} style={{ marginRight: "10px" }} onClick={() => toggleTodo(todo.id, todo.completed)}>
              {todo.completed ? "undo" : "check"}
            </button>
            <button className={styles.btn} onClick={() => removeTodo(todo.id)}>
              delete
            </button>
          </div>
        ))}
      </main>
    </div>
  );
};

export default Zustand;
